### ISSUE TITLE
Define an order direction by default

### ISSUE THREAD

**Issue by MathRobin** [MathRobin/sql-select-generator#2]
All SQL servers don't need ASC or DESC to work. Most of them (all ? ), consider ASC as default value. You should be allowed to enforce the presence of ASC or DESC by default in the request generated.

Like setOrderDefaultWay('DESC')

**Comment by benjaminW78** [comment]
do you mean at your request instance initialization ?

**Comment by MathRobin** [comment]
Yep, like for #useLowercase method
